# This is a basic workflow to help you get started with Actions

name: test steps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NAME: "null"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: action1
        run: exit 0
        id: action1
      - name: action2
        if: ${{ success() }}
        run: |
          echo ${NAME} success
          echo current directory: ${PWD}
          exit 1
        env:
          NAME: actions
        working-directory: /home
        shell: bash
        id: action2
        continue-on-error: true
      - name: action3
        if: steps.action1.outcome == 'success'
        run: |
          echo last step: ${{steps.action2.outcome}}
          echo ${NAME} success
          echo current directory: ${PWD}
