# This is a basic workflow to help you get started with Actions

name: test strategy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_run:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
        name: ['joie','tom','invoker']
        include: 
          - name: 'joie'
            os: ubuntu-18.04
        exclude:
          - os: macos-11
            name: 'invoker'
      fail-fast: false
      max-parallel: 2    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: who am i
        run: |
          echo i am ${{matrix.name}}, from ${{ matrix.os }}
          echo os: ${{ runner.os }}, name: ${{ runner.name }}
